### ISSUE TITLE
关于IB_DESIGNABLE实时显示的问题

### ISSUE THREAD

**Issue by shicang1990** [MakeZL/UIView-Category#2]
我在OC代码里用IB_DESIGNABLE用于SB的实时刷新，但是只能用您的那几个属性设置，我按照类似您的方式自己添加的shadow属性完全没反应，关于IB_DESIGNABLE和shadow网上资料不多，没找到解决方法，您之前是测试过这个问题，所以才没加入shadow的属性吗？

**Comment by MakeZL** [comment]
is ok!
